name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set working directory to wellcomlab-refactor
        run: cd wellcomlab-refactor
      - run: ls # 현재 디렉토리의 파일을 확인
      - name: Install dependencies
        run: npm install
      - run: ls # npm 설치 후 파일 확인
      - name: Build project
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WELLCOMLAB_70A36 }}
          projectId: wellcomlab-70a36